title: Advanced Algorithms

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

url: "https://kapsitis.github.io"
baseurl: "/lu-advanced-algorithms"

# Apply the default layout to pages unless they specify another one.
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default