plugins {
    id 'java-library'
}

plugins {
    id "application"
}
apply plugin : "java"
ext {
    javaMainClass = "lv.ddgatve.crypto.AES128"
}
application {
    mainClassName = javaMainClass
}


java {
    sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7
}

dependencies {
    implementation files('../lib-java/bcprov-jdk18on-171.jar')
    implementation files('../lib-java/bcpkix-jdk18on-171.jar')
}
